export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";

export const SHOW_ALL_ITEMS = "SHOW_ALL_ITEMS";
export const SHOW_ACCESSORY_ITEMS = "SHOW_ACCESSORY_ITEMS";
export const SHOW_DRONE_ITEMS = "SHOW_DRONE_ITEMS";
export const SHOW_CAMERA_ITEMS = "SHOW_CAMERA_ITEMS";
export const SHOW_SALE_ITEMS = "SHOW_SALE_ITEMS";
export const SHOW_BESTSELLER_ITEMS = "SHOW_BESTSELLER_ITEMS";
export const SHOW_NEWPRODUCT_ITEMS = "SHOW_NEWPRODUCT_ITEMS";
export const SHOW_CART_ITEMS = "SHOW_CART_ITEMS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_ALL_TO_CART = "ADD_ALL_TO_CART";
export const ADD_DRONE_TO_CART = "ADD_DRONE_TO_CART";
export const ADD_CAMERA_TO_CART = "ADD_CAMERA_TO_CART";
export const ADD_ACCESSORY_TO_CART = "ADD_ACCESSORY_TO_CART";
export const ADD_SALE_TO_CART = "ADD_SALE_TO_CART";
export const ADD_BESTSELLER_TO_CART = "ADD_BESTSELLER_TO_CART";
export const ADD_NEWPRODUCTS_TO_CART = "ADD_NEWPRODUCTS_TO_CART";

export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";

export const INCREASE_ITEM_QUANTITY = "INCREASE_ITEM_QUANTITY";
export const DECREASE_ITEM_QUANTITY = "DECREASE_ITEM_QUANTITY";

export const SUBMIT_CART = "SUBMIT_CART";

export const MAKE_ALL = "MAKE_ALL";
export const MAKE_DRONES = "MAKE_DRONES";
export const MAKE_CAMERAS = "MAKE_CAMERAS";
export const MAKE_ACCESSORIES = "MAKE_ACCESSORIES";
export const MAKE_SALES = "MAKE_SALES";
export const MAKE_BESTSELLERS = "MAKE_BESTSELLERS";
export const MAKE_NEWPRODUCTS = "MAKE_NEWPRODUCTS";

export const SUBMIT_SHOPPING = "SUBMIT_SHOPPING";
